<a href="https://colab.research.google.com/github/ragaslan/i-am-learning-pytorch/blob/main/Basic_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [18]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([5,10,15,20])

In [4]:
# addition
t_sum = t1 + t2
t_sum

tensor([ 6, 12, 18, 24])

In [5]:
# addition long hand
t_sum2 = torch.add(t1, t2)
t_sum2

tensor([ 6, 12, 18, 24])

In [6]:
# substraction
t_sub = t1 - t2
t_sub

tensor([ -4,  -8, -12, -16])

In [7]:
# substraction long hand
t_sub2 = torch.sub(t1, t2)
t_sub2

tensor([ -4,  -8, -12, -16])

In [8]:
# multiplication
t_mul = t1 * t2
t_mul

tensor([ 5, 20, 45, 80])

In [10]:
# multiplication long hand
t_mul2 = torch.mul(t1, t2)
t_mul2

tensor([ 5, 20, 45, 80])

In [5]:
# division
t_div = t1 / t2
t_div

tensor([0.2000, 0.2000, 0.2000, 0.2000])

In [6]:
# division long hand
t_div2 = torch.div(t1,t2)
t_div2

tensor([0.2000, 0.2000, 0.2000, 0.2000])

In [8]:
# remainder
t_rem = t2 % t1
t_rem

tensor([0, 0, 0, 0])

In [10]:
# exponents / power
t_pow = t2 ** t1
t_pow

tensor([     5,    100,   3375, 160000])

In [11]:
# power long hand
t_pow2 = torch.pow(t2, t1)
t_pow2

tensor([     5,    100,   3375, 160000])

In [23]:
# reassignment
t1.add(t2) # no
t1

tensor([11, 22, 33, 44])

In [24]:
#reassignment
t1.add_(t2) # yes
t1

tensor([16, 32, 48, 64])