<a href="https://colab.research.google.com/github/ragaslan/i-am-learning-pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

TENSORS

In [ ]:
tensors = torch.randn(2,3)

tensors

tensor([[-1.7365,  0.3142, -0.2321],
        [-0.7997,  0.2296,  1.9890]])

In [ ]:
tensors.dtype


torch.float32

In [ ]:
torch.zeros(3)

tensor([0., 0., 0.])

In [ ]:
my_torch = torch.arange(10)

my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch2 = my_torch.reshape(5,2)

torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
# reshape if we dont know the number of items using -1
torch_example = torch.arange(15)
torch_example

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
torch_example = torch_example.reshape(3,-1);
torch_example

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
torch_example = torch_example.reshape(5,-1)

torch_example

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
torch4 = torch.arange(15)

torch4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
torch6 = torch4.view(3,5)
torch6

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
torch4[2] = 1453

torch4

tensor([   0,    1, 1453,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14])

In [ ]:
torch6

tensor([[   0,    1, 1453,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14]])

In [ ]:
torch4

tensor([   0,    1, 1453,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14])

In [ ]:
torch5 = torch4.reshape(3,5)

torch5

tensor([[   0,    1, 1453,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14]])

In [ ]:
torch5[1:,1:4]

tensor([[ 6,  7,  8],
        [11, 12, 13]])